steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--build-arg",
        "MONGO_ATLAS=$_MONGO_ATLAS",
        "--build-arg",
        "MONGO_ATLAS_USER=$_MONGO_ATLAS_USER",
        "--build-arg",
        "MONGO_ATLAS_PASSWORD=$_MONGO_ATLAS_PASSWORD",
        "--build-arg",
        "VITE_DATABASE=$_VITE_DATABASE",
        "-t",
        "gcr.io/$PROJECT_ID/platzmonster-service:$COMMIT_SHA",
        ".",
      ]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/platzmonster-service:$COMMIT_SHA"]
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "platzmonster-service"
      - "--image"
      - "gcr.io/$PROJECT_ID/platzmonster-service:$COMMIT_SHA"
      - "--region"
      - "15"
images:
  - "gcr.io/$PROJECT_ID/platzmonster-service:$COMMIT_SHA"
