FROM node:16-alpine

# USER root
# RUN apk add --update python3 py3-pip make g++

ARG MONGO_ATLAS
ARG MONGO_ATLAS_PASSWORD
ARG MONGO_ATLAS_USER
ARG VITE_DATABASE

ENV PORT=6005
ENV MONGO_ATLAS=$MONGO_ATLAS
ENV MONGO_ATLAS_USER=$MONGO_ATLAS_USER
ENV MONGO_ATLAS_PASSWORD=$MONGO_ATLAS_PASSWORD
ENV VITE_DATABASE=$VITE_DATABASE

USER node
ADD --chown=node:node . /app
WORKDIR /app
RUN npm ci && npm run build

CMD ["node", "build/index.js"]

EXPOSE ${PORT}
